name = "admin-dashboard"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
API_BASE_URL = "https://api.uinsports.com"

[env.preview.vars]
API_BASE_URL = "https://api-dev.uinsports.com"
